language: cpp
dist: xenial
compiler:
  - clang
  - gcc
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
script: mkdir build && cd build && cmake .. && make
